words = ["taxi", "cab", "standing", "cricket",
         "alarm clock","tool", "banana peel",
         "flagpole","money","hardwork",
         "ballpoint pen","sunburn", "wedding",
         "ring" ,"spy", "aunt","puzzle piece",
         "pawn","astronaut", "tennis" ,"shoes",
         "trip","outer space","batteries",
         "doghouse","campsite","plumber",
         "throne","logo", "mute","stove",
         "windmill", "nightmare","wristwatch",
         "eat","matchstick","sprinkler",
         "living room","laugh","elf,headache",
         "Internet","phone"]
